### ISSUE TITLE
什么时候提供一个可用的 Ubuntu 镜像

### ISSUE THREAD

**Issue by wonderfullook** [radxa-build/rock-3c#10]
如题，现有的 b42 镜像都没成功运行
![image](https://github.com/radxa-build/rock-3c/assets/38576701/a1ef3745-0313-447e-9044-9aebe88a0648)

**Comment by RadxaYuntian** [comment]
由于Rockchip SDK并不支持Ubuntu，我们一直都没有官方提供这个系统的支持，仅仅只是自动生成了镜像。我们之后不会再提供没有官方支持的版本。
