### ISSUE TITLE
whats the username/password

### ISSUE THREAD

**Issue by hrshovon** [radxa-build/rock-3c#2]
u: rock p: rock does not work
u: radxa p:radxa does not work

**Comment by RadxaYuntian** [comment]
The account is not included in the image, and will be created during the first boot. It is important to not forcefully shut down the SBC during the first boot setup, which is running in the background automatically.

We plan to release a new image tonight so you can give it another try.

**Comment by RadxaYuntian** [comment]
Latest build is available at: https://github.com/radxa-build/rock-3c/releases/tag/b33
