### ISSUE TITLE
Linux Kernel 6 support?

### ISSUE THREAD

**Issue by couling** [radxa-build/rock-3c#3]
AFAIK there is only currently support for Linux Kernel 4.19 which hits EOL December 2024. A whole version has been and gone and current linux releases are 6.x. What support will there be for a 6x Kernel?

**Comment by RadxaYuntian** [comment]
Our system uses Rockchip SDK kernel which is a different kind of beast compared to mainline kernel. Currently the latest release of Rockchip SDK uses "5.10" kernel. However, we currently have some blocking issues with this version, and a few more RK356X products also need to have a production image first. The current plan for upgrading is in Q3 or Q4.

**Comment by couling** [comment]
@RadxaYuntian you are saying that the current plan for 5.10 is Q3 or Q4?  Why about Linux kernel 6.x?

**Comment by RadxaYuntian** [comment]
> Currently the latest release of Rockchip SDK uses "5.10" kernel.

**Comment by couling** [comment]
Excuse my confusion here, the [images on your website](https://wiki.radxa.com/Rock3/downloads) have Linux 4.19 not 5.10. So it's a little ambiguous what you mean by "upgrade"?

Are you saying that you intend to have the "blocking issues" resolved by Q4 or upgrading the SDK to 6.x by Q4?

**Comment by RadxaYuntian** [comment]
We are looking to upgrade RK356X product to 5.10. We cannot upgrade to a unreleased 6.x SDK.
