### ISSUE TITLE
No wifi in ubuntu server

### ISSUE THREAD

**Issue by Simzie** [radxa-build/rock-3c#4]
I've installed rock-3c_ubuntu_jammy_cli_b33.img.xz with Belena Etcher to an SD card and inserted it into a brand new Rock 3 Model C. I've tried updating the before.txt file to include wifi details and after that failed I've tried without.

Can log into the server however:

`nmcli device status`
wlan0 wifi unavailable

`nmcli radio wifi`
enabled

`nmcli dev wifi list`
Shows the columns but doesn't list anything. I have even put this so it is touching the router and nothing.

`sudo nmcli dev wifi connect my_SSID`
Error: No network with SSID 'my_SSID' found.

I've tried turning the wifi off then back on to no avail and the guides offer no support. I've tried the xfce version but it just spins around and around on the splash screen. CM256SM chip and see there were issues a year ago but was supposed to be fixed.

Decidedly frustrating and an exceedingly poor first experience. What is happening here?

**Comment by RadxaYuntian** [comment]
Please first test with our Debian Xfce version, since this is the officially supported image. Ubuntu is provided as-is with no testing.

**Comment by Simzie** [comment]
Ok thanks. I _now_ see the comment that:

> Not all images are officially supported by Radxa. Some of them are only provided as-is with no warranty. Please read below for detailed explanations.

I would mention that there's not really any opportunity to read the "detailed explanations", as there isn't really any (maybe there is something in the links but that's a step too far to get the message across". Looking in the forum you have a lot of questions around wifi and to find out that they're just provided as is, without drivers, feels like you've just wasted my, and others, time needlessly.

**Comment by RadxaYuntian** [comment]
We will still fix the issue if we can reproduce it. With that being said, on our release note we only mention Debian system.

**Comment by Simzie** [comment]
Thanks Yuntian. I appreciate the quick response but would also recommend you amend the github page to make this more obvious.
