### ISSUE TITLE
Debian image CLI 5.10.160 not booting

### ISSUE THREAD

**Issue by mbol** [radxa-build/rock-3c#5]
I've tried the image Debian 5.10.160-1-rk356x with XFCE on Rock 3C and is working correctly. 
Trying the Debian 5.10.160-1-rk356x only CLI it won't boot, here the log where it get blocked:

U-Boot menu
1:      Debian GNU/Linux 11 (bullseye) 5.10.160-1-rk356x
2:      Debian GNU/Linux 11 (bullseye) 5.10.160-1-rk356x (rescue target)
Enter choice: 1:        Debian GNU/Linux 11 (bullseye) 5.10.160-1-rk356x
Retrieving file: /boot/vmlinuz-5.10.160-1-rk356x
Retrieving file: /boot/initrd.img-5.10.160-1-rk356x
append: root=UUID=b7d69630-7c7b-4d6f-8b46-19892353d001 quiet splash loglevel=4 rw earlycon consoleblank=0 console=tty0 console=ttyFIQ0,1500000n8 console=ttyAML0,115200n8 console=ttyS2,1500000n8 console=ttyS0,1500000n8 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
Retrieving file: /usr/lib/linux-image-5.10.160-1-rk356x/rockchip/rk3566-rock-3c.dtb
Moving Image from 0x2080000 to 0x2200000, end=3d40000
## Flattened Device Tree blob at 0a100000
   Booting using the fdt blob at 0xa100000
Working FDT set to a100000
Host not halted after 16000 microseconds.
Host not halted after 16000 microseconds.
   Loading Ramdisk to 7c701000, end 7cecc0ef ... OK
ERROR: reserving fdt memory region failed (addr=0 size=0 flags=0)
ERROR: reserving fdt memory region failed (addr=0 size=0 flags=0)
   Loading Device Tree to 000000007c6d7000, end 000000007c7009fd ... OK
Working FDT set to 7c6d7000

Starting kernel ...

[   10.905371] fiq_debugger fiq_debugger.0: IRQ fiq not found
[   10.905426] fiq_debugger fiq_debugger.0: IRQ wakeup not found
[   10.905459] fiq_debugger_probe: could not install nmi irq handler
[   12.470791] rk-pcie 3c0000000.pcie: IRQ msi not found
[   12.470883] rk-pcie 3c0000000.pcie: Missing *config* reg space
[   12.471141] rk-pcie 3c0000000.pcie: Missing *config* reg space
[   12.471221] rk-pcie 3c0000000.pcie: invalid resource
[   12.479780] mpp-iep2 fdef0000.iep: allocate roi buffer failed
[   12.500246] arm-scmi firmware:scmi: Failed. SCMI protocol 22 not active.
[   12.523218] dwhdmi-rockchip fe0a0000.hdmi: IRQ index 1 not found
[   12.526732] no ATF memory for init
[   12.549482] no ATF memory for init
[   12.561267] rk_gmac-dwmac fe010000.ethernet: no regulator found
[   12.908816] rkcifhw fdfe0000.rkcif: can't request region for resource [mem 0xfdfe0000-0xfdfe7fff]
[   12.912480] rkisp_hw fdff0000.rkisp: can't request region for resource [mem 0xfdff0000-0xfdffffff]
[   12.923624] arm-scmi firmware:scmi: Failed. SCMI protocol 17 not active.
[   12.932950] rksfc_base v1.1 2016-01-08
[   13.066750] rk817-battery rk817-battery: Failed to find matching dt id
[   13.067331] rk817-charger rk817-charger: Failed to find matching dt id
[   13.094524] mpp_rkvenc fdf40000.rkvenc: Failed to get leakage
[   13.095438] mpp_rkvenc fdf40000.rkvenc: failed to find power_model node
[   13.095505] mpp_rkvenc fdf40000.rkvenc: failed to initialize power model
[   13.095536] mpp_rkvenc fdf40000.rkvenc: failed to get dynamic-coefficient
[   13.098396] mpp_rkvdec2 fdf80200.rkvdec: shared_niu_a is not found!
[   13.098470] rkvdec2_init:1022: No niu aclk reset resource define
[   13.098505] mpp_rkvdec2 fdf80200.rkvdec: shared_niu_h is not found!
[   13.098532] rkvdec2_init:1025: No niu hclk reset resource define
[   13.099860] mpp_rkvdec2 fdf80200.rkvdec: failed to find power_model node
[   13.099902] mpp_rkvdec2 fdf80200.rkvdec: failed to initialize power model
[   13.099932] mpp_rkvdec2 fdf80200.rkvdec: failed to get dynamic-coefficient
[   13.267490] headset_interrupt:get pin level again, pin=148,i=0
[   15.354098] rk-pcie 3c0000000.pcie: PCIe Link Fail
[   15.354184] rk-pcie 3c0000000.pcie: failed to initialize host

**Comment by gjm19761** [comment]
i get the exact same issue in debian cli, its pcie : failed ro initilize host and hangs

**Comment by RadxaYuntian** [comment]
The issue was again on the GPU driver. I tried to fix it properly, but found out that Debian 11 does not support the GPU used in RK356X. [The Mesa commit adding the support](https://gitlab.freedesktop.org/mesa/mesa/-/commit/e1959f0f5990fc73e78a7431a800c623b6fc5208) is released in newer version than the one shipped in Debian 11. As such we decided to put this on hold for now (since we would work with Rockchip Debian 12 SDK soon), and recommend users to use the Desktop variant for now.

**Comment by RadxaYuntian** [comment]
panfrost is disabled since https://github.com/radxa-repo/bsp/commit/17340a79b0a123e5adfa309c9cd598a0f8b2b327.

**Comment by RadxaYuntian** [comment]
User who wish to have CLI image booting can check [this forum post](https://forum.radxa.com/t/rock-3b-custom-cli-build-doesnt-boot/19740/3?u=radxayuntian).

**Comment by rabee05** [comment]
"since we would work with Rockchip Debian 12 SDK soon" how soon can we get Debian 12 image? we have been working on Debian 11 and we unable to build our software.

**Comment by RadxaYuntian** [comment]
The one for RK3588 is released, and I got to the desktop yesterday on ROCK 5B. RK356X will come later according to Rockchip's roadmap released in 2023/09:

![](https://www.cnx-software.com/wp-content/uploads/2023/11/Rockchip-SDK-release-schedule.png)

**Comment by pavelvasev** [comment]
Hi! Is there any news on Linux kernel 6.* support for Radxa Zero 3? Maybe any forecast?

**Comment by RadxaYuntian** [comment]
Nothing from Rockchip right now. We are still working on RK3588 Linux 6.1, though rkr2 was released by the end of April. With above projection we are 1 release away from RK356X.

**Comment by outhud** [comment]
Hi @RadxaYuntian, is there any news on Debian 12 and/or Linux 6.1 for RK3566 / Zero 3W?

Hoping to use an official Debian CLI OS for this board soon :)

**Comment by RadxaYuntian** [comment]
No news. When we are going to work on it you would see repos like `rock-3c-6_1` just like our current RK3588 bring up. Until then there is nothing.

We will stop provide CLI image in the future due to lack of testing and supporting resources.

**Comment by defencedog** [comment]
@RadxaYuntian For future releases of zero3 will you be using `libmali` close source drivers or `mesa` opensource `panfrost` drivers? Because former does expose `/dev/mali0` HW interface

**Comment by RadxaYuntian** [comment]
We are looking to use `panfrost` in Debian 12 by default.

**Comment by Tatutovich** [comment]
Armbian has already been released on the 6th Linux kernel, but it has its own problems
As a result, there are plans to release 12 Debian for Radxa 3W, where the video driver will work correctly for the desktop?

**Comment by defencedog** [comment]
@Tatutovich I am having no problem using Armbian Noble Server + CASAOS
```
OS: Armbian (24.8.4) aarch64 
Host: Radxa ZERO 3 
Kernel: 6.1.75-vendor-rk35xx 
Uptime: 1 day, 7 hours, 54 mins 
Packages: 913 (dpkg) 
Shell: bash 5.2.21 
Terminal: ttyd 
CPU: (4) @ 1.800GHz 
Memory: 2709MiB / 3732MiB 
```

**Comment by Tatutovich** [comment]
> @Tatutovich I am having no problem using Armbian Noble Server + CASAOS
1) Unresolved problem with RAdxa Camera 8M in Armbian Noble, a topic was created on the Armbian forum, I am not the only one with the problem, but there is no answer to the problem.

2) I need a desktop with working video drivers, they work in Armbian, but for some reason after the update there were problems, an error of the Wi-Fi indication service began to appear, the load on the processor in idle by the desktop process, because of which heating and power consumption,
and most importantly, an error of unavailability of resources
This problem is only in the version with the desktop (both), **in the server and IOT there are no such problems except for the camera.**
The most interesting thing is that I installed Armbian Noble on Orange CM4 with the same processor from Orange 3b, and there are no such problems with overheating, high load on the processor in idle, errors about unavailability of resources. But I want to use Radxa 3W

In Radxa OS (Debian 11) everything works (which excludes the problem with the hardware), there is no overheating in idle and after updates, except that there is no working video driver (no hardware acceleration) for the desktop

I would be satisfied with a working RAdxa Camera 8M on Armbian, but so far there is no progress in solving the problem.

Therefore, it would be nice if 12 Debian from Radxa came out where everything would work as it should

**Comment by defencedog** [comment]
@Tatutovich I am using `3E` with CasaOS so I cannot say anything about WIFI. I am using it for `paperless-ngx` & CPU works at 100% loading during OCR operations. I installed [dual-fan](https://www.cytron.io/p-raspberry-pi-zero-2w-heatsink-enclosure-with-dual-fan) for temperature control

Regarding GPU my `jellyfin` works with HW VPU acceleration so drivers are OK as well
How you are using 8M Camera? It must need some overlay activated I am sure. I fyou can identify that overlay you can easily copy it to Armbian `/boot/dtb/overlay`

**Comment by Tatutovich** [comment]
Overlay is activated via armbian-add-overlay.
If you are interested, here is a topic on the Armbian forum
https://forum.armbian.com/topic/42688-radxa-camera-8m-not-working

**Comment by defencedog** [comment]
@Tatutovich then it definitely means driver / firmware is absent. In OS where it is is running is there any specific kernel module loaded `modprobe` after attaching camera?

**Comment by Tatutovich** [comment]
@defencedog   I found a topic on the Armbian forum, where it is indicated that there are no drivers in the kernel
https://forum.armbian.com/topic/33639-csi2-drivers-for-rk35xx/
Therefore, it would be relevant for Radxa to release a build where the GPU driver would work correctly and the CSI camera

**Comment by defencedog** [comment]
CSI camera I cannot test (I dont have relevant hardware) However GPU panfrost is working & my Jellyfin has VPU acceleration

**Comment by RadxaYuntian** [comment]
Just as an update that we now have access to Rockchip RK356X Debian 12 SDK. Currently there is no scheduled plan for upgrading existing products.

**Comment by krzkraw** [comment]
@RadxaYuntian question related as Zero 3 uses RK3566 - there is no plans to update it also?

**Comment by RadxaYuntian** [comment]
Generally products using the same SoC will be supported at a similar level, so there is no specific policy for ZERO 3.

We now have access to RK356X Debian 12 SDK, and we are currently evaluating it.

**Comment by samveen** [comment]
@RadxaYuntian What linux kernel version is used as the base for  `RK356X Debian 12 SDK` ? If we have some idea, maybe we can help with smaller tasks around the build and support.

**Comment by RadxaYuntian** [comment]
It will be Rockchip 6.1 kernel. The porting job is currently on going.

**Comment by Elaugaste** [comment]
I hope that the camera will work better, now the camera "8m imx219" works very badly (colors and brightness are terrible)

**Comment by RadxaYuntian** [comment]
We had similar camera related issue with some RK3588 devices that are fixed by upgrade the Rockchip SDK. RK356X will use the same fixed SDK as those RK3588 devices, so we are expecting improvement on this area.
