### ISSUE TITLE
Is 4k supported ? Display resolution max 1920x1080

### ISSUE THREAD

**Issue by ozkansen** [radxa-build/rock-3c#8]
Even with a 4k monitor installed, the screen resolution is at most 1920x1080. The device I'm using is a Rock 3 model c. The technical specifications show 4k support.

**Comment by RadxaYuntian** [comment]
3C is [software limited to FHD](https://github.com/radxa/kernel/pull/145/files) due to lackluster hardware performance. The product will not officially support 4K.

Can you link me the documentation where is says 3C support 4K? I'll have our marketing team corrects it ASAP.

**Comment by ozkansen** [comment]
On the page that opens in the link below, it is written that it gives 2k and 4k images with the same cpu.

https://radxa.com/products/compute-module/cm3/#techspec

**Comment by RadxaYuntian** [comment]
CM3 is not 3C. They are 2 different products with different specs.

**Comment by ozkansen** [comment]
![image](https://github.com/radxa-build/rock-3c/assets/4196157/9b7361ae-4389-4a44-9352-cd3c2d3f3534)

![image](https://github.com/radxa-build/rock-3c/assets/4196157/a9d1f327-ed08-4d90-a398-bb28d449d874)

It's written on the boxes

**Comment by RadxaYuntian** [comment]
I'll check with the design team.
