### ISSUE TITLE
Upgrade command breaks the system on 1GB RAM of Rock 3C

### ISSUE THREAD

**Issue by mako220** [radxa-build/rock-3c#9]
Using the latest b42 debian xfce image with only CLI, using rsetup -> System Update, crashes the system with out of memory errors. 
![PXL_20240315_222608222 MP](https://github.com/radxa-build/rock-3c/assets/17583932/92b7e2df-4cb4-42e1-8d47-370d9ccfa57b)

**Comment by RadxaYuntian** [comment]
@CodeChenL Please check if you can reproduce this.

**Comment by CodeChenL** [comment]
> @CodeChenL Please check if you can reproduce this.

Need to manually update [/usr/lib/rsetup/cli/u-boot-menu.sh](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/cli/u-boot-menu.sh) and run sudo dpkg --configure -a to continue the update

**Comment by RadxaYuntian** [comment]
We need to fix dkms build oom. What you described will left user with broken Wi-Fi.

**Comment by RadxaYuntian** [comment]
After checking with the log again, it appears to be a rsetup bug where when updating the overlay it consumes a large amount of memory. We have fixed it since [v0.3.46](https://github.com/radxa-pkg/rsetup/releases/tag/0.3.46) but later versions are not released yet.

**Comment by mako220** [comment]
I did what @CodeChenL suggested and the the error did not reproduce. Also, the wifi connection still works for now. The device has AP6256 wifi chip if that helps. Thanks for the help guys.
